### ISSUE TITLE
cranelift-module allows func declare local -> export, but faerie doesn't

### ISSUE THREAD

**Issue by bjorn3** [bytecodealliance/wasmtime#1132]
```
thread 'rustc' panicked at 'inconsistent declarations: IncompatibleDeclaration { old: Defined(Function(FunctionDecl { scope: Local, visibility: Default, align: None })), new: Defined(Function(FunctionDecl { scope: Global, visibility: Default, align: None })) }', src/libcore/result.rs:1165:5
stack backtrace:
[...]
  15: core::result::unwrap_failed
             at src/libcore/result.rs:1165
  16: core::result::Result<T,E>::expect
             at /rustc/032a53a06ce293571e51bbe621a5c480e8a28e95/src/libcore/result.rs:960
  17: <cranelift_faerie::backend::FaerieBackend as cranelift_module::backend::Backend>::declare_function
             at /home/bjorn/.cargo/git/checkouts/cranelift-af8713b52459e6cd/ee6fe21/cranelift-faerie/src/backend.rs:127
  18: cranelift_module::module::Module<B>::declare_function
             at /home/bjorn/.cargo/git/checkouts/cranelift-af8713b52459e6cd/ee6fe21/cranelift-module/src/module.rs:426
[...]
```

```rust
module.declare_function(name, Linkage::Local, sig).unwrap();
module.declare_function(name, Linkage::Export, sig).unwrap();
```

Either cranelift-module should forbid this, or faerie should allow this. Preferably the later.

**Comment by bjorn3** [comment]
cranelift-faerie has since been removed.
