### ISSUE TITLE
Panic during debuginfo processing

### ISSUE THREAD

**Issue by bjorn3** [bytecodealliance/wasmtime#144]
```
 lldb -- wasmtime -g rust_binary.wasm
(lldb) run
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:347:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: rust_begin_unwind
             at src/libstd/panicking.rs:308
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::panicking::panic
             at src/libcore/panicking.rs:49
   9: wasmtime_debug::transform::transform_dwarf
  10: wasmtime_debug::emit_debugsections_image
  11: wasmtime_jit::compiler::Compiler::compile
  12: wasmtime_jit::instantiate::RawCompiledModule::new
  13: wasmtime_jit::instantiate::instantiate
  14: wasmtime_jit::context::Context::instantiate_module
  15: wasmtime::handle_module
  16: wasmtime::main
  17: std::rt::lang_start::{{closure}}
  18: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  19: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:85
  20: std::rt::lang_start_internal
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  21: main
  22: __libc_start_main
  23: _start
```

Unfortunately github considers the wasm file too big, even when compressed (~140MB). If anyone knows of a service to upload it, please tell me.

You may be able to reproduce it by cloning https://github.com/bjorn3/rust/tree/compile_rustc_for_wasm and following the instructions at the top of the README. (You will need to subsitute `wasm32-unknown-wasi` with `wasm32-wasi`.)

**Comment by bjorn3** [comment]
Backtrace with debuginfo:

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:347:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: rust_begin_unwind
             at src/libstd/panicking.rs:308
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::panicking::panic
             at src/libcore/panicking.rs:49
   9: wasmtime_debug::transform::transform_dwarf
             at /rustc/af98304b9a006e2f9a367b1f79dd7655f243c150/src/libcore/macros.rs:12
             at wasmtime-debug/src/transform.rs:548
             at wasmtime-debug/src/transform.rs:610
  10: wasmtime_debug::emit_debugsections_image
             at wasmtime-debug/src/lib.rs:64
  11: wasmtime_jit::compiler::Compiler::compile
             at wasmtime-jit/src/compiler.rs:110
  12: wasmtime_jit::instantiate::RawCompiledModule::new
             at wasmtime-jit/src/instantiate.rs:80
  13: wasmtime_jit::instantiate::instantiate
             at wasmtime-jit/src/instantiate.rs:254
  14: wasmtime_jit::context::Context::instantiate_module
             at wasmtime-jit/src/context.rs:105
             at wasmtime-jit/src/context.rs:132
  15: wasmtime::handle_module
             at src/wasmtime.rs:294
  16: wasmtime::main
             at src/wasmtime.rs:279
  17: std::rt::lang_start::{{closure}}
             at /rustc/af98304b9a006e2f9a367b1f79dd7655f243c150/src/libstd/rt.rs:64
  18: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  19: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:85
  20: std::rt::lang_start_internal
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  21: main
  22: __libc_start_main
  23: _start
```

The unwrap at

https://github.com/CraneStation/wasmtime/blob/1c0efd03b37489247ad2ac66f0e2b54bc29a9a1f/wasmtime-debug/src/transform.rs#L548

failed.

**Comment by bjorn3** [comment]
I uploaded it to firefox send. The download link https://send.firefox.com/download/8125bf27e3560dbe/#BGQ7Qu8XiNH6EqL12DpIjg will remain valid for 100 downloads and 7 days.

**Comment by yurydelendik** [comment]
Is it still an issue?

**Comment by bjorn3** [comment]
I saw another problem:

```
$ lldb -- wasmtime -g rustc_binary.wasm
(lldb) run
error: failed to process main module `../../target/wasm32-wasi/release/rustc_binary.wasm`
    caused by: Debug information error: UnexpectedEof(ReaderOffsetId(11060999730))
```

https://send.firefox.com/download/344bba782e6da813/#yYsCDH8pDUj3GC24fYHLlQ (for own reference when needing to re-upload: mac wasmtime_crashes/issue-144-2-rustc_binary.wasm.zip)

**Comment by alexcrichton** [comment]
It looks like the most recent version of this is an error rather than a panic, so I'm going to close this as "likely fixed". If it still crops up though please feel free to resubmit a new issue! I'd recommend using `gzip` to compress the wasm module and upload it directly to GitHub if possible as well.

**Comment by bjorn3** [comment]
> If it still crops up though please feel free to resubmit a new issue!

+1 If I try to compile rustc for wasm again and notice this bug I will submit a new issue.

> I'd recommend using gzip to compress the wasm module and upload it directly to GitHub if possible as well.

It was still way too large after that last time.
