### ISSUE TITLE
Wasi-NN ci example failed

### ISSUE THREAD

**Issue by gusye1234** [bytecodealliance/wasmtime#3948]
Thanks for filing a bug report! Please fill out the TODOs below.

**Note: if you want to report a security issue, please read our [security policy](https://bytecodealliance.org/security)!**

### Steps to Reproduce

* run `bash ci/run-wasi-nn-example.sh`

### Expected Results

A success inference should happen for this test, outputting the classification results for the mobilenet.

### Actual Results

A panic happened at the step of 
```rust
        wasi_nn::compute(context).unwrap();
```
It reported the error as :
```shell
Host error: BackendError(BackendAccess(parameter mismatch))
thread 'main' panicked at 'not implemented', crates/wasi-nn/src/witx.rs:17:45
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
### Versions and Environment

Wasmtime version or commit: commit head at e8ae3c0afdc7347d3de80c554353257efda2bbaa

Operating system: Ubuntu 20.04

Architecture: x86_64

OpenVINO version: 2021.4.582
### Extra Info

My OpenVINO installed dir is on `/opt/intel/openvino_2021`, so I have to change one line in the `ci/run-wasi-nn-example.sh` to
```shell
source /opt/intel/openvino_2021/bin/setupvars.sh
```
but I don't think that's the problem.

**Comment by gusye1234** [comment]
Full backtrace is here
```
[setupvars.sh] OpenVINO environment initialized
    Finished dev [unoptimized + debuginfo] target(s) in 5.36s
~/wasmtime/crates/wasi-nn/examples/classification-example ~/wasmtime
    Finished release [optimized] target(s) in 0.14s
~/wasmtime
    Finished dev [unoptimized + debuginfo] target(s) in 6.19s
     Running `target/debug/wasmtime run --mapdir 'fixture::/root/openvino_fixtures' /root/openvino_fixtures/wasi-nn-example.wasm --wasi-modules=experimental-wasi-nn`
Read graph XML, first 50 characters: <?xml version="1.0" ?>
<net name="mobilenet_v2_1.0
Read graph weights, size in bytes: 13956476
Loaded graph into wasi-nn with ID: 0
Created wasi-nn execution context with ID: 0
Read input tensor, size in bytes: 602112
Host error: BackendError(BackendAccess(parameter mismatch))
thread 'main' panicked at 'not implemented', crates/wasi-nn/src/witx.rs:17:45
stack backtrace:
   0:     0x56004aa5fa4c - std::backtrace_rs::backtrace::libunwind::trace::h91c465e73bf6c785
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x56004aa5fa4c - std::backtrace_rs::backtrace::trace_unsynchronized::hae9da36f5d58b5f3
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x56004aa5fa4c - std::sys_common::backtrace::_print_fmt::h7f499fa126a7effb
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x56004aa5fa4c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3e2b509ce2ce6007
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x56004aa86f9c - core::fmt::write::h753c7571fa063ecb
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/fmt/mod.rs:1168:17
   5:     0x56004aa58aa3 - std::io::Write::write_fmt::h2815c0519c99ba09
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/io/mod.rs:1660:15
   6:     0x56004aa620c2 - std::sys_common::backtrace::_print::h64941a6fc8b0ed9b
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x56004aa620c2 - std::sys_common::backtrace::print::hcf25e43e1a9b0766
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x56004aa620c2 - std::panicking::default_hook::{{closure}}::h78d3e6cf97fc623d
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:211:50
   9:     0x56004aa61ca5 - std::panicking::default_hook::hda898f8d3ad1a5ae
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:228:9
  10:     0x56004aa62713 - std::panicking::rust_panic_with_hook::h1a5ea2d6c23051aa
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:606:17
  11:     0x56004aa62402 - std::panicking::begin_panic_handler::{{closure}}::h07f549390938b73f
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:500:13
  12:     0x56004aa5fef4 - std::sys_common::backtrace::__rust_end_short_backtrace::h5ec3758a92cfb00d
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:139:18
  13:     0x56004aa62169 - rust_begin_unwind
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
  14:     0x5600490cfd01 - core::panicking::panic_fmt::h3a79a6a99affe1d5
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
  15:     0x5600490cfc4d - core::panicking::panic::h97167cd315d19cd4
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:48:5
  16:     0x560049422084 - wasmtime_wasi_nn::witx::<impl wasmtime_wasi_nn::witx::types::UserErrorConversion for wasmtime_wasi_nn::ctx::WasiNnCtx>::nn_errno_from_wasi_nn_error::hf4b55e0bc8b56f4d
                               at /root/wasmtime/crates/wasi-nn/src/witx.rs:17:45
  17:     0x5600491685b8 - wasmtime_wasi_nn::witx::wasi_ephemeral_nn::set_input::{{closure}}::hf0dd54022d4b1a4e
                               at /root/wasmtime/crates/wasi-nn/src/witx.rs:6:1
  18:     0x560049258efa - tracing::span::Span::in_scope::h357ef6f5da237da6
                               at /root/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tracing-0.1.31/src/span.rs:1091:9
  19:     0x560049166822 - wasmtime_wasi_nn::witx::wasi_ephemeral_nn::set_input::h21e40e093cc70a7c
                               at /root/wasmtime/crates/wasi-nn/src/witx.rs:6:1
  20:     0x56004916dc21 - wasmtime_wasi_nn::witx::wasi_ephemeral_nn::add_to_linker::{{closure}}::h5c2dd2b76d894e2d
                               at /root/wasmtime/crates/wasi-nn/src/witx.rs:6:1
  21:     0x5600491c1b0f - <F as wasmtime::func::IntoFunc<T,(wasmtime::func::Caller<T>,A1,A2,A3),R>>::into_func::wasm_to_host_shim::{{closure}}::{{closure}}::h029385688ad2ce0a
                               at /root/wasmtime/crates/wasmtime/src/func.rs:1893:41
  22:     0x56004912068d - core::ops::function::FnOnce::call_once::h134dd316713a2333
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:227:5
  23:     0x5600491094ac - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h0ed288d1197d920b
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panic/unwind_safe.rs:271:9
  24:     0x5600492d5e3a - std::panicking::try::do_call::h4c5ab10ccbeac1bb
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:406:40
  25:     0x5600492df2eb - __rust_try
  26:     0x5600492d1dd2 - std::panicking::try::hd55d31f55d8c3744
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:370:19
  27:     0x5600492674cc - std::panic::catch_unwind::h51b4b8f4c8b947c9
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panic.rs:133:14
  28:     0x5600491c0d7a - <F as wasmtime::func::IntoFunc<T,(wasmtime::func::Caller<T>,A1,A2,A3),R>>::into_func::wasm_to_host_shim::{{closure}}::hd913e7c8f9ad8ed3
                               at /root/wasmtime/crates/wasmtime/src/func.rs:1888:29
  29:     0x560049197106 - wasmtime::func::Caller<T>::with::h85c65baca66367ae
                               at /root/wasmtime/crates/wasmtime/src/func.rs:1672:9
  30:     0x5600491bcff0 - <F as wasmtime::func::IntoFunc<T,(wasmtime::func::Caller<T>,A1,A2,A3),R>>::into_func::wasm_to_host_shim::h7addf7b81507d9a1
                               at /root/wasmtime/crates/wasmtime/src/func.rs:1879:34
  31:     0x7fb61545a1d7 - <unknown>
  32:     0x7fb615458f3f - <unknown>
  33:     0x7fb615459c82 - <unknown>
  34:     0x7fb615459bc7 - <unknown>
  35:     0x7fb615463668 - <unknown>
  36:     0x7fb615459596 - <unknown>
  37:     0x7fb61545706e - <unknown>
  38:     0x7fb615484b1e - <unknown>
  39:     0x7fb615484bc0 - <unknown>
  40:     0x56004918b83d - wasmtime::func::Func::call_unchecked::{{closure}}::h67a44e4750d46d0a
                               at /root/wasmtime/crates/wasmtime/src/func.rs:799:13
  41:     0x56004915406c - wasmtime_runtime::traphandlers::catch_traps::call_closure::h0840ee8827ee02fc
                               at /root/wasmtime/crates/runtime/src/traphandlers.rs:193:18
  42:     0x56004a5e4eea - wasmtime_setjmp
                               at /root/wasmtime/crates/runtime/src/helpers.c:55:3
  43:     0x560049154038 - wasmtime_runtime::traphandlers::catch_traps::{{closure}}::hf60fe2c5951928a3
                               at /root/wasmtime/crates/runtime/src/traphandlers.rs:181:9
  44:     0x5600491548c2 - wasmtime_runtime::traphandlers::CallThreadState::with::{{closure}}::ha0b6a6e90c48e4d1
                               at /root/wasmtime/crates/runtime/src/traphandlers.rs:231:38
  45:     0x56004911234b - wasmtime_runtime::traphandlers::tls::set::h2561d962449b52c5
                               at /root/wasmtime/crates/runtime/src/traphandlers.rs:481:12
  46:     0x56004915438d - wasmtime_runtime::traphandlers::CallThreadState::with::h6c6ff9ae16204d24
                               at /root/wasmtime/crates/runtime/src/traphandlers.rs:231:19
  47:     0x560049153ad7 - wasmtime_runtime::traphandlers::catch_traps::h1bff7e654c707f33
                               at /root/wasmtime/crates/runtime/src/traphandlers.rs:180:12
  48:     0x56004918fc45 - wasmtime::func::invoke_wasm_and_catch_traps::ha7b68f43f1dc4864
                               at /root/wasmtime/crates/wasmtime/src/func.rs:1210:22
  49:     0x56004918b78b - wasmtime::func::Func::call_unchecked::h479459478e9f9634
                               at /root/wasmtime/crates/wasmtime/src/func.rs:798:9
  50:     0x56004918c7ba - wasmtime::func::Func::call_impl::h04a65515f80a4926
                               at /root/wasmtime/crates/wasmtime/src/func.rs:948:13
  51:     0x56004918b2a1 - wasmtime::func::Func::call::h0116c273a8d66505
                               at /root/wasmtime/crates/wasmtime/src/func.rs:755:9
  52:     0x5600490fdb79 - wasmtime::linker::Linker<T>::module::{{closure}}::{{closure}}::ha8aa085ff0f1aab8
                               at /root/wasmtime/crates/wasmtime/src/linker.rs:666:33
  53:     0x56004918e2d8 - wasmtime::func::Func::invoke::h453893fb2c30f29f
                               at /root/wasmtime/crates/wasmtime/src/func.rs:1022:9
  54:     0x56004918ac84 - wasmtime::func::Func::new::{{closure}}::h9a2caa98695f668f
                               at /root/wasmtime/crates/wasmtime/src/func.rs:327:17
  55:     0x56004919c6bf - wasmtime::func::HostFunc::new_unchecked::{{closure}}::{{closure}}::hc0783649221ec593
                               at /root/wasmtime/crates/wasmtime/src/func.rs:2053:54
  56:     0x560049194d75 - wasmtime::func::Caller<T>::with::h5860ddc166cf3b72
                               at /root/wasmtime/crates/wasmtime/src/func.rs:1672:9
  57:     0x56004919c66d - wasmtime::func::HostFunc::new_unchecked::{{closure}}::h71d79d55dd305099
                               at /root/wasmtime/crates/wasmtime/src/func.rs:2053:13
  58:     0x56004929e1a2 - wasmtime::trampoline::func::stub_fn::{{closure}}::he5ceae7a9ff13f42
                               at /root/wasmtime/crates/wasmtime/src/trampoline/func.rs:52:9
  59:     0x56004912051d - core::ops::function::FnOnce::call_once::h0c6a744d060f163b
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:227:5
  60:     0x56004910aa09 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h95575ff11b848bf2
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panic/unwind_safe.rs:271:9
  61:     0x5600492da11f - std::panicking::try::do_call::he1e2ae803335a46a
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:406:40
  62:     0x5600492df2eb - __rust_try
  63:     0x5600492cae04 - std::panicking::try::h4ff6660b2ce3d042
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:370:19
  64:     0x560049268591 - std::panic::catch_unwind::hf5612dd4c6ba10c5
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panic.rs:133:14
  65:     0x56004929e092 - wasmtime::trampoline::func::stub_fn::h5817ef73bb798f83
                               at /root/wasmtime/crates/wasmtime/src/trampoline/func.rs:45:18
  66:     0x7fb6156a201f - <unknown>
  67:     0x7fb6156a2006 - <unknown>
  68:     0x56004918b83d - wasmtime::func::Func::call_unchecked::{{closure}}::h67a44e4750d46d0a
                               at /root/wasmtime/crates/wasmtime/src/func.rs:799:13
  69:     0x56004915406c - wasmtime_runtime::traphandlers::catch_traps::call_closure::h0840ee8827ee02fc
                               at /root/wasmtime/crates/runtime/src/traphandlers.rs:193:18
  70:     0x56004a5e4eea - wasmtime_setjmp
                               at /root/wasmtime/crates/runtime/src/helpers.c:55:3
  71:     0x560049154038 - wasmtime_runtime::traphandlers::catch_traps::{{closure}}::hf60fe2c5951928a3
                               at /root/wasmtime/crates/runtime/src/traphandlers.rs:181:9
  72:     0x5600491548c2 - wasmtime_runtime::traphandlers::CallThreadState::with::{{closure}}::ha0b6a6e90c48e4d1
                               at /root/wasmtime/crates/runtime/src/traphandlers.rs:231:38
  73:     0x56004911234b - wasmtime_runtime::traphandlers::tls::set::h2561d962449b52c5
                               at /root/wasmtime/crates/runtime/src/traphandlers.rs:481:12
  74:     0x56004915438d - wasmtime_runtime::traphandlers::CallThreadState::with::h6c6ff9ae16204d24
                               at /root/wasmtime/crates/runtime/src/traphandlers.rs:231:19
  75:     0x560049153ad7 - wasmtime_runtime::traphandlers::catch_traps::h1bff7e654c707f33
                               at /root/wasmtime/crates/runtime/src/traphandlers.rs:180:12
  76:     0x56004918fc45 - wasmtime::func::invoke_wasm_and_catch_traps::ha7b68f43f1dc4864
                               at /root/wasmtime/crates/wasmtime/src/func.rs:1210:22
  77:     0x56004918b78b - wasmtime::func::Func::call_unchecked::h479459478e9f9634
                               at /root/wasmtime/crates/wasmtime/src/func.rs:798:9
  78:     0x56004918c7ba - wasmtime::func::Func::call_impl::h04a65515f80a4926
                               at /root/wasmtime/crates/wasmtime/src/func.rs:948:13
  79:     0x56004918b501 - wasmtime::func::Func::call::h405a2f93eab55bab
                               at /root/wasmtime/crates/wasmtime/src/func.rs:755:9
  80:     0x56004914c18c - wasmtime_cli::commands::run::RunCommand::invoke_func::h023a031ff1b9a156
                               at /root/wasmtime/src/commands/run.rs:384:9
  81:     0x56004914affc - wasmtime_cli::commands::run::RunCommand::load_main_module::hd4af7f7d3f7746a9
                               at /root/wasmtime/src/commands/run.rs:327:13
  82:     0x56004914914c - wasmtime_cli::commands::run::RunCommand::execute::hfb55e534c0dc0b42
                               at /root/wasmtime/src/commands/run.rs:207:15
  83:     0x5600490dc397 - wasmtime::WasmtimeApp::execute::hcc5a8604b5f42ce0
                               at /root/wasmtime/src/bin/wasmtime.rs:57:29
  84:     0x5600490dc506 - wasmtime::main::hea0a6527efc26532
                               at /root/wasmtime/src/bin/wasmtime.rs:65:5
  85:     0x5600490dfa7b - core::ops::function::FnOnce::call_once::hdddd6aa978d082f7
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:227:5
  86:     0x5600490e08ae - std::sys_common::backtrace::__rust_begin_short_backtrace::heed7a699243b63c9
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:123:18
  87:     0x5600490df921 - std::rt::lang_start::{{closure}}::h0caae1164f8bf1e9
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/rt.rs:145:18
  88:     0x56004aa5f100 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h443f738a8e9f947a
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:259:13
  89:     0x56004aa5f100 - std::panicking::try::do_call::h1e21ba261ba489ec
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:406:40
  90:     0x56004aa5f100 - std::panicking::try::h6afd48af8b6c96ac
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:370:19
  91:     0x56004aa5f100 - std::panic::catch_unwind::h85dd95e0bab7fb60
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panic.rs:133:14
  92:     0x56004aa5f100 - std::rt::lang_start_internal::{{closure}}::h038455e697c8b03e
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/rt.rs:128:48
  93:     0x56004aa5f100 - std::panicking::try::do_call::h6b0ad65979f3077a
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:406:40
  94:     0x56004aa5f100 - std::panicking::try::h010108d314169ac6
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:370:19
  95:     0x56004aa5f100 - std::panic::catch_unwind::hff397f912b1535c2
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panic.rs:133:14
  96:     0x56004aa5f100 - std::rt::lang_start_internal::h52e73755f77c7dd9
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/rt.rs:128:20
  97:     0x5600490df8f0 - std::rt::lang_start::hd7fc2b86c332571e
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/rt.rs:144:17
  98:     0x5600490dd73c - main
  99:     0x7fb6158cc0b3 - __libc_start_main
 100:     0x5600490d049e - _start
 101:                0x0 - <unknown>
```

**Comment by alexcrichton** [comment]
cc @abrown

**Comment by gusye1234** [comment]
Sure! 
So maybe I can export the model from the newer version of OpenVINO to fix this problem.

**Comment by brianjjones** [comment]
@gusye1234 I've found the issue and created a this PR #3956. Thanks for catching the issue.

@abrown This is ready to review, thanks.
