### ISSUE TITLE
wasmtime run -g panics with an assertion failure

### ISSUE THREAD

**Issue by TerrorJack** [bytecodealliance/wasmtime#4838]
Thanks for filing a bug report! Please fill out the TODOs below.

**Note: if you want to report a security issue, please read our [security policy](https://bytecodealliance.org/security)!**

### Test Case

See [here](https://drive.google.com/file/d/1jY44Xfm3lAvEBJrl4dTT-Jjnmy83RocA/view?usp=sharing, https://drive.google.com/file/d/1mNLI5EWCbXP5sYKyjJd-8mW60eU2n1Fx/view?usp=sharing) for the uploaded wasm files.

`ghcapi.wasm` is the original module, `work.wasm` is a reduced case using `wasm-reduce` that still has the same error message

### Steps to Reproduce

* Run `wasmtime -g ghcapi.wasm`

### Expected Results

* The wasm module should run as usual, print some stuff and then exit, as demonstrated when running without `-g`.

### Actual Results

`wasmtime` panics with the following error message (with `RUST_BACKTRACE=full`):

```
thread 'main' panicked at 'assertion failed: range_start < range_end', crates/cranelift/src/debug/transform/expression.rs:689:13
stack backtrace:
   0:     0x5587ebe76ecd - std::backtrace_rs::backtrace::libunwind::trace::h8217d0a8f3fd2f41
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x5587ebe76ecd - std::backtrace_rs::backtrace::trace_unsynchronized::h308103876b3af410
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5587ebe76ecd - std::sys_common::backtrace::_print_fmt::hc208018c6153605e
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x5587ebe76ecd - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf89a7ed694dfb585
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x5587ebe9bafc - core::fmt::write::h21038c1382fe4264
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/fmt/mod.rs:1197:17
   5:     0x5587ebe716d1 - std::io::Write::write_fmt::h7dbb1c9a3c254aef
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/io/mod.rs:1672:15
   6:     0x5587ebe78675 - std::sys_common::backtrace::_print::h4e8889719c9ddeb8
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x5587ebe78675 - std::sys_common::backtrace::print::h1506fe2cb3022667
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x5587ebe78675 - std::panicking::default_hook::{{closure}}::hd9d7ce2a8a782440
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:295:22
   9:     0x5587ebe78396 - std::panicking::default_hook::h5b16ec25444b1b5d
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:314:9
  10:     0x5587ebe78c06 - std::panicking::rust_panic_with_hook::hb0138cb6e6fea3e4
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:698:17
  11:     0x5587ebe78ab9 - std::panicking::begin_panic_handler::{{closure}}::h4cb67095557cd1aa
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:586:13
  12:     0x5587ebe77384 - std::sys_common::backtrace::__rust_end_short_backtrace::h2bfcac279dcdc911
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x5587ebe78829 - rust_begin_unwind
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
  14:     0x5587eb748653 - core::panicking::panic_fmt::h1de71520faaa17d3
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
  15:     0x5587eb74851d - core::panicking::panic::h467ee1bf554babeb
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:48:5
  16:     0x5587eba3cef5 - wasmtime_cranelift::debug::transform::expression::ValueLabelRangesBuilder::process_label::hf532659b119fbb47
  17:     0x5587eba3a64e - wasmtime_cranelift::debug::transform::expression::CompiledExpression::build_with_locals::h94cb640973090c65
  18:     0x5587eba48e67 - wasmtime_cranelift::debug::transform::simulate::generate_simulated_dwarf::he7201147bc039110
  19:     0x5587eba2e421 - wasmtime_cranelift::debug::transform::transform_dwarf::h4cc8ecfb26179c64
  20:     0x5587eba0705a - wasmtime_cranelift::debug::write_debuginfo::emit_dwarf::hb8abb8a59201d97d
  21:     0x5587eba366c9 - <wasmtime_cranelift::compiler::Compiler as wasmtime_environ::compilation::Compiler>::emit_obj::h0cbae1e4e6431f4f
  22:     0x5587eb8dd6d8 - wasmtime::module::Module::build_artifacts::h63074b6d048e6fdf
  23:     0x5587eb8dc94a - wasmtime::module::Module::from_binary::h1de553a53a70a8f4
  24:     0x5587eb7791df - wasmtime::module::Module::from_file::h2d36c5e0e488253a
  25:     0x5587eb81f4ac - wasmtime_cli::commands::run::RunCommand::load_module::h832f336f27abe8ab
  26:     0x5587eb81cdd5 - wasmtime_cli::commands::run::RunCommand::execute::hbb855870fdf993ff
  27:     0x5587eb74b1ca - wasmtime::main::h6e34b60a66e1a2f3
  28:     0x5587eb7502e3 - std::sys_common::backtrace::__rust_begin_short_backtrace::hc6c27247cc182a18
  29:     0x5587eb7502f9 - std::rt::lang_start::{{closure}}::he9b1e35cc41819bd
  30:     0x5587ebe6b54e - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h4937aaa125c8d4b2
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/ops/function.rs:280:13
  31:     0x5587ebe6b54e - std::panicking::try::do_call::h6f5c70e8b0a34f92
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:492:40
  32:     0x5587ebe6b54e - std::panicking::try::h68766ba264ecf2e2
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:456:19
  33:     0x5587ebe6b54e - std::panic::catch_unwind::hc36033d2f9cc04af
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panic.rs:137:14
  34:     0x5587ebe6b54e - std::rt::lang_start_internal::{{closure}}::h78c037f4a1a28ded
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/rt.rs:128:48
  35:     0x5587ebe6b54e - std::panicking::try::do_call::he6e1fffda4c750ee
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:492:40
  36:     0x5587ebe6b54e - std::panicking::try::h48a77ddbb2f4c87a
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:456:19
  37:     0x5587ebe6b54e - std::panic::catch_unwind::hfa809b06a550a9e7
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panic.rs:137:14
  38:     0x5587ebe6b54e - std::rt::lang_start_internal::h4db69ed48eaca005
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/rt.rs:128:20
  39:     0x5587eb74b3e2 - main
  40:     0x7f0b59c21d90 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  41:     0x7f0b59c21e40 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:392:3
  42:     0x5587eb7488ed - <unknown>
  43:                0x0 - <unknown>
```

### Versions and Environment

Wasmtime version or commit: `wasmtime-cli 0.40.0`

Operating system: `Ubuntu 22.04.1`

Architecture: `x86_64`

**Comment by bjorn3** [comment]
Thanks for the bug report! Please note the following:

https://github.com/bytecodealliance/wasmtime/issues/4669#issuecomment-1210997950

> We currently don't have anyone on the project who understands our DWARF-handling code well and has time to work on it; so while this is definitely a bug, it's not likely to have a fast resolution. We do have an intent to have someone eventually focus on this, as priorities allow, so we should keep this issue open. Just wanted to give some context on the current situation...

**Comment by jameysharp** [comment]
I'm going to close this as a duplicate of #4669. That said, when we're able to spend the time on fixing this bug, I bet it will help to have samples from multiple compilers, so thank you for this report!
