### ISSUE TITLE
Riscv float abi variant handling

### ISSUE THREAD

**Issue by bjorn3** [bytecodealliance/wasmtime#4994]
Riscv has different abi variants which pass floating point arguments differently. This is controlled independently of the used target features and the linker checks that object files with different abi variants are not linked together. Currently Cranelift doesn't handle this at all and effectively uses the double float abi unconditionally. We will need a way to specify the float abi (soft, single, double), use this float abi even if the target features would allow the double float abi and expose a way for cranelift-object to get the chosen float abi to put in the `e_flags` field of an elf binary.

**Comment by yuyang-ok** [comment]
~~~
+    /// SystemV riscv64 have different ABI variants.
+    SystemVRiscv(SystemVRiscv),
+}
+
+pub enum SystemVRiscv {
+    ILP32,
+    ILP32F,
+    ILP32D,
+    LP64,
+    LP64F,
+    LP64D,
+    LP64Q,
+}
+
+impl SystemVRiscv {
+    pub fn is_32(self) -> bool {
+        match self {
+            Self::ILP32 | Self::ILP32F | Self::ILP32D => true,
+            _ => false,
+        }
+    }
+    pub fn is_64() -> bool {
+        match self {
+            Self::LP64 | Self::LP64F | Self::LP64D | Self::LP64Q => true,
+            _ => false,
+        }
+    }
 }
 
 impl CallConv {
yuyang@yuyang-Inspiron-7590:~/projects/wasmtime/cranelift$ 
~~~
@bjorn3   I want to add these callconv, looks ok??

**Comment by yuyang-ok** [comment]
~~~
+    /// SystemV riscv64 have different ABI variants.
+    SystemVRiscv(SystemVRiscv),
+}
+
+pub struct SystemVRiscv {
+    float_call_conv: RiscvFloatCallConv,
+}
+
+pub enum RiscvFloatCallConv {
+    Soft,
+    Single,
+    Double,
+    Quad,
+}
+
+impl SystemVRiscv {
+    pub fn is_32(self) -> bool {
+        match self {
+            Self::ILP32 | Self::ILP32F | Self::ILP32D => true,
+            _ => false,
+        }
+    }
+    pub fn is_64() -> bool {
+        match self {
+            Self::LP64 | Self::LP64F | Self::LP64D | Self::LP64Q => true,
+            _ => false,
+        }
+    }
 }
~~~

@bjorn3  looks fine???

**Comment by bjorn3** [comment]
That should work I think. I do think there is still a need for an isa flag to specify which float call conv should be returned by the default_call_conv field.

**Comment by yuyang-ok** [comment]
> I do think there is still a need for an isa flag to specify which float call conv should be returned by the default_call_conv field.

I am not understand this. I didn't see any connection between `isa flags` and `default_call_conv`.

**Comment by bjorn3** [comment]
The `TargetIsa` has a `frontend_config` method, which returns a value with the `default_call_conv` field. To make this method return the right value in the `default_call_conv` field, there has to be an isa flag to choose it.

**Comment by yuyang-ok** [comment]
@bjorn3 Sorry, I must missed that, I have add the setting.

**Comment by yuyang-ok** [comment]
~~~
  Running tests/filetests.rs (/home/yuyang/projects/wasmtime/target/riscv64gc-unknown-linux-gnu/debug/deps/filetests-ac71876a5d2b4558)
thread 'worker #7' panicked at 'not implemented: ISA flag float_abi of kind Enum', cranelift/filetests/src/test_run.rs:117:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'worker #8' panicked at 'not implemented: ISA flag float_abi of kind Enum', cranelift/filetests/src/test_run.rs:117:13
thread 'worker #6' panicked at 'not implemented: ISA flag float_abi of kind Enum', cranelift/filetests/src/test_run.rs:117:13
thread 'worker #9' panicked at 'not implemented: ISA flag float_abi of kind Enum', cranelift/filetests/src/test_run.rs:117:13
thread 'worker #6' panicked at 'not implemented: ISA flag float_abi of kind Enum', cranelift/filetests/src/test_run.rs:117:13
thread 'worker #7' panicked at 'not implemented: ISA flag float_abi of kind Enum', cranelift/filetests/src/test_run.rs:117:13
thread 'worker #6' panicked at 'not implemented: ISA flag float_abi of kind Enum', cranelift/filetests/src/test_run.rs:117:13
thread 'worker #8' panicked at 'not implemented: ISA flag float_abi of kind Enum', cranelift/filetests/src/test_run.rs:117:13
thread 'worker #7' panicked at 'not implemented: ISA flag float_abi of kind Enum', cranelift/filetests/src/test_run.rs:
~~~

I am getting this error.

**Comment by bjorn3** [comment]
Not sure how to deal with that.

**Comment by bjorn3** [comment]
Not sure how to deal with that.

**Comment by yuyang-ok** [comment]
This is indeed not unimplemented.:-)

**Comment by afonso360** [comment]
The runtest suite tries to [check if the hardware supports the flags](https://github.com/bytecodealliance/wasmtime/blob/e63771f2d921cdce440620dbf38bd3e186747b1e/cranelift/filetests/src/test_run.rs#L98-L99) that were requested for this test. 

This is done so that if a particular test tries to compile the code with `has_avx512` and the host machine does not support `avx512` we don't try to run the code and cause an illegal instruction error.

Currently that code only supports boolean values, I don't mind extending it to also support enums, but that would also mean that we have to choose some variant of the riscv float abi to be the one that is detected by `cranelift-native` and tests would only be able to use that one in particular or they would be skipped.

That variant also has to be the default one, or we skip all riscv tests.

**Comment by yuyang-ok** [comment]
https://bytecodealliance.zulipchat.com/#narrow/stream/206238-general/topic/add_enum.20can't.20have.20default.20value.3F.3F
