### ISSUE TITLE
Cranelift: regalloc panic on riscv64 when compiling libcore

### ISSUE THREAD

**Issue by bjorn3** [bytecodealliance/wasmtime#4996]
Thanks for filing an issue! Please fill out the TODOs below.

### `.clif` Test Case

```
function u0:5() -> i128, i64 system_v {
                                block0:
@0001                               v5 = bconst.b1 false
@0001                               brz v5, block3  ; v5 = false
                                    jump block1

                                block1:
@0003                               v12 = iconst.i64 0
@0003                               v13 = uextend.i128 v12  ; v12 = 0
@000a                               jump block5(v13)

                                block3:
@000b                               v21 = iconst.i128 0
@000a                               jump block5(v21)  ; v21 = 0

                                block5(v23: i128):
@0011                               v29 = iconst.i64 0
@001c                               return v23, v29  ; v29 = 0
}
```

### Steps to Reproduce

* Compile it for riscv64

### Expected Results

It compiles

### Actual Results

```
thread 'main' panicked at 'assertion failed: from_bundle.is_valid()', /home/bjorn/.cargo/registry/src/github.com-1ecc6299db9ec823/regalloc2-0.4.1/src/ion/merge.rs:364:13
stack backtrace:
[...]
   2: core::panicking::panic
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:48:5
   3: regalloc2::ion::merge::<impl regalloc2::ion::data_structures::Env<F>>::merge_vreg_bundles
             at /home/bjorn/.cargo/registry/src/github.com-1ecc6299db9ec823/regalloc2-0.4.1/src/ion/merge.rs:364:13
   4: regalloc2::ion::<impl regalloc2::ion::data_structures::Env<F>>::init
             at /home/bjorn/.cargo/registry/src/github.com-1ecc6299db9ec823/regalloc2-0.4.1/src/ion/mod.rs:98:9
   5: regalloc2::ion::run
             at /home/bjorn/.cargo/registry/src/github.com-1ecc6299db9ec823/regalloc2-0.4.1/src/ion/mod.rs:125:5
   6: regalloc2::run
             at /home/bjorn/.cargo/registry/src/github.com-1ecc6299db9ec823/regalloc2-0.4.1/src/lib.rs:1460:5
   7: cranelift_codegen::machinst::compile::compile
             at ./codegen/src/machinst/compile.rs:41:9
   8: cranelift_codegen::isa::riscv64::Riscv64Backend::compile_vcode
             at ./codegen/src/isa/riscv64/mod.rs:65:9
   9: <cranelift_codegen::isa::riscv64::Riscv64Backend as cranelift_codegen::isa::TargetIsa>::compile_function
             at ./codegen/src/isa/riscv64/mod.rs:76:40
```

### Versions and Environment

Cranelift version or commit: 3fa545bd89d6e18e6e85eab57499ee9c9f5032f2

Operating system: N/A

Architecture: riscv64

### Extra Info

Causes libcore compilation to fail with cg_clif.

**Comment by yuyang-ok** [comment]
@bjorn3 Sorry see https://github.com/bytecodealliance/wasmtime/pull/4998.
