### ISSUE TITLE
Panic on a simple `wat` file

### ISSUE THREAD

**Issue by gabriel-fallen** [bytecodealliance/wasmtime#602]
Running
```sh
$ RUST_BACKTRACE=full wasmtime --invoke=test1 ifelse.wat
```
gives this stacktrace:
```
thread 'thread '<unnamed><unnamed>' panicked at '' panicked at 'slice index starts at 18446744073709551615 but ends at 0slice index starts at 18446744073709551615 but ends at 0', ', src/libcore/slice/mod.rssrc/libcore/slice/mod.rs::25912591::55

stack backtrace:
   0:     0x5595d03922f4 - backtrace::backtrace::libunwind::trace::hda41dbcdfba36aa0
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1:     0x5595d03922f4 - backtrace::backtrace::trace_unsynchronized::h1a8d6e1f8cb3f5d4
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2:     0x5595d03922f4 - std::sys_common::backtrace::_print_fmt::h610c4127487e10da
                               at src/libstd/sys_common/backtrace.rs:76
   3:     0x5595d03922f4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h0722dc552e01bd1d
                               at src/libstd/sys_common/backtrace.rs:60
   4:     0x5595d03b621c - core::fmt::write::h01edf6dd68a42c9c
                               at src/libcore/fmt/mod.rs:1030
   5:     0x5595d038ed87 - std::io::Write::write_fmt::hf15985f193f03c04
                               at src/libstd/io/mod.rs:1412
   6:     0x5595d0394e95 - std::sys_common::backtrace::_print::hd8d5d08a1795e743
                               at src/libstd/sys_common/backtrace.rs:64
   7:     0x5595d0394e95 - std::sys_common::backtrace::print::hf89a79e3921a2366
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x5595d0394e95 - std::panicking::default_hook::{{closure}}::h3a8f42beb3bb8ae3
                               at src/libstd/panicking.rs:196
   9:     0x5595d0394b86 - std::panicking::default_hook::h8f803b0bc31a5c37
                               at src/libstd/panicking.rs:210
  10:     0x5595d0395595 - std::panicking::rust_panic_with_hook::h825f041245da8739
                               at src/libstd/panicking.rs:473
  11:     0x5595d0395132 - std::panicking::continue_panic_fmt::hbe0378e33481e81b
                               at src/libstd/panicking.rs:380
  12:     0x5595d0395026 - rust_begin_unwind
                               at src/libstd/panicking.rs:307
  13:     0x5595d03b227a - core::panicking::panic_fmt::h527855ce0bc891f6
                               at src/libcore/panicking.rs:85
  14:     0x5595d03b26d6 - core::slice::slice_index_order_fail::h76ed01bbeda02eb2
                               at src/libcore/slice/mod.rs:2591
  15:     0x5595d0199782 - cranelift_wasm::state::func_state::FuncTranslationState::peekn::h32ce059f242c443d
  16:     0x5595d008ff2d - cranelift_wasm::code_translator::translate_operator::heb14c0ab91daaa5c
  17:     0x5595d00abc72 - cranelift_wasm::func_translator::FuncTranslator::translate::h8545c005722ab684
  18:     0x5595d009d4f3 - <rayon::iter::map_with::MapWithFolder<C,U,F> as rayon::iter::plumbing::Folder<T>>::consume_iter::with::{{closure}}::hfa9678aba389bf71
  19:     0x5595d00a33a9 - core::iter::adapters::map_try_fold::{{closure}}::hde3b546dfe53ba2d
  20:     0x5595d00a59ee - <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold::h7c0501c906286963
  21:     0x5595d00ab359 - <rayon::iter::fold::FoldFolder<C,ID,F> as rayon::iter::plumbing::Folder<T>>::consume_iter::h7c82de6c316ee896
  22:     0x5595d0079aca - rayon::iter::plumbing::bridge_producer_consumer::helper::ha5756b16686603b2
  23:     0x5595d0066658 - std::panicking::try::do_call::h52529c525a2a3535
  24:     0x5595d03997fa - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  25:     0x5595d00aecf4 - <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::h32e22d0936d05214
  26:     0x5595d018700e - rayon_core::registry::WorkerThread::wait_until_cold::h5c427dc1d4c0148d
  27:     0x5595d01857ca - rayon_core::registry::ThreadBuilder::run::h27134a2c85de72f0
  28:     0x5595cff9793a - std::sys_common::backtrace::__rust_begin_short_backtrace::h4c79e311800162f3
  29:     0x5595cff99759 - std::panicking::try::do_call::h2d5dcc74e23e68ca
  30:     0x5595d03997fa - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  31:     0x5595cff9abc4 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h0714bcb4e032f475
  32:     0x5595d038764f - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h483711add4ba2330
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/boxed.rs:922
  33:     0x5595d0398bf0 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h7605b45eb29ed0be
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/boxed.rs:922
  34:     0x5595d0398bf0 - std::sys_common::thread::start_thread::h557b0c2dc4449562
                               at src/libstd/sys_common/thread.rs:13
  35:     0x5595d0398bf0 - std::sys::unix::thread::Thread::new::thread_start::h7c2a7f9b68fe4bba
                               at src/libstd/sys/unix/thread.rs:79
  36:     0x7fdf9db1b6db - start_thread
  37:     0x7fdf9d62c88f - __clone
  38:                0x0 - <unknown>
stack backtrace:
   0:     0x5595d03922f4 - backtrace::backtrace::libunwind::trace::hda41dbcdfba36aa0
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1:     0x5595d03922f4 - backtrace::backtrace::trace_unsynchronized::h1a8d6e1f8cb3f5d4
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2:     0x5595d03922f4 - std::sys_common::backtrace::_print_fmt::h610c4127487e10da
                               at src/libstd/sys_common/backtrace.rs:76
   3:     0x5595d03922f4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h0722dc552e01bd1d
                               at src/libstd/sys_common/backtrace.rs:60
   4:     0x5595d03b621c - core::fmt::write::h01edf6dd68a42c9c
                               at src/libcore/fmt/mod.rs:1030
   5:     0x5595d038ed87 - std::io::Write::write_fmt::hf15985f193f03c04
                               at src/libstd/io/mod.rs:1412
   6:     0x5595d0394e95 - std::sys_common::backtrace::_print::hd8d5d08a1795e743
                               at src/libstd/sys_common/backtrace.rs:64
   7:     0x5595d0394e95 - std::sys_common::backtrace::print::hf89a79e3921a2366
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x5595d0394e95 - std::panicking::default_hook::{{closure}}::h3a8f42beb3bb8ae3
                               at src/libstd/panicking.rs:196
   9:     0x5595d0394b86 - std::panicking::default_hook::h8f803b0bc31a5c37
                               at src/libstd/panicking.rs:210
  10:     0x5595d0395595 - std::panicking::rust_panic_with_hook::h825f041245da8739
                               at src/libstd/panicking.rs:473
  11:     0x5595d0395132 - std::panicking::continue_panic_fmt::hbe0378e33481e81b
                               at src/libstd/panicking.rs:380
  12:     0x5595d0395026 - rust_begin_unwind
                               at src/libstd/panicking.rs:307
  13:     0x5595d03b227a - core::panicking::panic_fmt::h527855ce0bc891f6
                               at src/libcore/panicking.rs:85
  14:     0x5595d03b26d6 - core::slice::slice_index_order_fail::h76ed01bbeda02eb2
                               at src/libcore/slice/mod.rs:2591
  15:     0x5595d0199782 - cranelift_wasm::state::func_state::FuncTranslationState::peekn::h32ce059f242c443d
  16:     0x5595d008ff2d - cranelift_wasm::code_translator::translate_operator::heb14c0ab91daaa5c
  17:     0x5595d00abc72 - cranelift_wasm::func_translator::FuncTranslator::translate::h8545c005722ab684
  18:     0x5595d009d4f3 - <rayon::iter::map_with::MapWithFolder<C,U,F> as rayon::iter::plumbing::Folder<T>>::consume_iter::with::{{closure}}::hfa9678aba389bf71
  19:     0x5595d00a33a9 - core::iter::adapters::map_try_fold::{{closure}}::hde3b546dfe53ba2d
  20:     0x5595d00a59ee - <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold::h7c0501c906286963
  21:     0x5595d00ab359 - <rayon::iter::fold::FoldFolder<C,ID,F> as rayon::iter::plumbing::Folder<T>>::consume_iter::h7c82de6c316ee896
  22:     0x5595d0079aca - rayon::iter::plumbing::bridge_producer_consumer::helper::ha5756b16686603b2
  23:     0x5595d0066585 - std::panicking::try::do_call::h38896e65fc596ad0
  24:     0x5595d03997fa - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  25:     0x5595d008d3c4 - rayon_core::join::join_context::{{closure}}::h56f92c27957054d4
  26:     0x5595d0066713 - std::panicking::try::do_call::hf1b24475b609d508
  27:     0x5595d03997fa - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  28:     0x5595d00af023 - <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::h44bad3d909c3a6c3
  29:     0x5595d018700e - rayon_core::registry::WorkerThread::wait_until_cold::h5c427dc1d4c0148d
  30:     0x5595d01857ca - rayon_core::registry::ThreadBuilder::run::h27134a2c85de72f0
  31:     0x5595cff9793a - std::sys_common::backtrace::__rust_begin_short_backtrace::h4c79e311800162f3
  32:     0x5595cff99759 - std::panicking::try::do_call::h2d5dcc74e23e68ca
  33:     0x5595d03997fa - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  34:     0x5595cff9abc4 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h0714bcb4e032f475
  35:     0x5595d038764f - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h483711add4ba2330
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/boxed.rs:922
  36:     0x5595d0398bf0 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h7605b45eb29ed0be
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/boxed.rs:922
  37:     0x5595d0398bf0 - std::sys_common::thread::start_thread::h557b0c2dc4449562
                               at src/libstd/sys_common/thread.rs:13
  38:     0x5595d0398bf0 - std::sys::unix::thread::Thread::new::thread_start::h7c2a7f9b68fe4bba
                               at src/libstd/sys/unix/thread.rs:79
  39:     0x7fdf9db1b6db - start_thread
  40:     0x7fdf9d62c88f - __clone
  41:                0x0 - <unknown>
```

The file is
```
(module
  (func $test1 (result i32)
    i32.const 1
    i32.const 2
    i32.lt_u
    if
      i32.const 42
    else
      i32.const 0
    end)
  (export "test1" (func $test1))
  (func $test2 (result i32)
    i32.const 1
    i32.const 2
    i32.eq
    if
      i32.const 0
    else
      i32.const 42
    end)
  (export "test2" (func $test2))
)
```

I'm just experimenting with WASM and kinda learning by trying random stuff so it might be totally wrong WASM. But I think `wasmtime` isn't supposed to panic even on wrong files. :)

**Comment by pepyakin** [comment]
This is interesting, looking at the stack trace it seems that this code gets into compilation machinery whereas it really shouldn't: it is invalid (missing `(result i32)` declaration for the `if` block). 

I wonder if it has something to do with recent migration to `wast` crate. @alexcrichton does `wast` crate performs validation when reading?

**Comment by gabriel-fallen** [comment]
It turned out that indeed the `wat` file was wrong and that was the reason for a crash. I forgot ` (result i32)` on `if`s. On this code:
```
(module
  (func $test1 (result i32)
    i32.const 1
    i32.const 2
    i32.lt_u
    if (result i32)
      i32.const 42
    else
      i32.const 0
    end)
  (export "test1" (func $test1))
  (func $test2 (result i32)
    i32.const 1
    i32.const 2
    i32.eq
    if (result i32)
      i32.const 0
    else
      i32.const 42
    end)
  (export "test2" (func $test2))
)
```
`wasmtime` runs fine and gives expected output.

**Comment by alexcrichton** [comment]
@pepyakin no the `wat` and `wast` crates do not perform any validation, they're just tasked with grabbing a binary blob for a wasm module, and if it happens to be text it converts it to binary on the fly

**Comment by pepyakin** [comment]
Then this is probably it. If there are no plans augumenting `wat`/`wast` crates with validation in the foreseable future, I think the best we can do (without resorting to `wabt` again) is either to pass the input code through validating parser from `wasmparser` or use the same parser on `cranelift-wasm` side.

**Comment by alexcrichton** [comment]
This was fixed in https://github.com/bytecodealliance/wasmtime/pull/621 where `Module::new` will now perform validation.

**Comment by gabriel-fallen** [comment]
That's nice! You people are doing really great job! :muscle:
