### ISSUE TITLE
Failure to instantiate valid empty Wasm module

### ISSUE THREAD

**Issue by fitzgen** [bytecodealliance/wasmtime#636]
Wasmtime fails to instantiate the valid, empty module:

```wat
(module)
```

Here is a Rust unit test:

```rust
#[test]
fn instantiate_empty_module() {
    // `(module)`
    let wasm = vec![0x0, 0x61, 0x73, 0x6d 0x01, 0x0, 0x0, 0x0];
    wasmtime_fuzzing::oracles::instantiate(&wasm, wasmtime_jit::CompilationStrategy::Auto);
}
```

**Comment by fitzgen** [comment]
Stack trace:

```
    #0 0x558c2f1ae511 in __sanitizer_print_stack_trace /rustc/f1b882b55805c342e46ee4ca3beeef1d1fa2044b/src/llvm-project/compiler-rt/lib/asan/asan_stack.cc:86:3
    #1 0x558c3306a949 in fuzzer::PrintStackTrace() /home/fitzgen/.cargo/git/checkouts/libfuzzer-sys-e07fde05820d7bc6/2542ae4/libfuzzer/FuzzerUtil.cpp:205
    #2 0x558c3306e562 in fuzzer::Fuzzer::CrashCallback() /home/fitzgen/.cargo/git/checkouts/libfuzzer-sys-e07fde05820d7bc6/2542ae4/libfuzzer/FuzzerLoop.cpp:232
    #3 0x558c3306e403 in fuzzer::Fuzzer::StaticCrashSignalCallback() /home/fitzgen/.cargo/git/checkouts/libfuzzer-sys-e07fde05820d7bc6/2542ae4/libfuzzer/FuzzerLoop.cpp:203
    #4 0x558c33058a8b in fuzzer::CrashHandler(int, siginfo_t*, void*) /home/fitzgen/.cargo/git/checkouts/libfuzzer-sys-e07fde05820d7bc6/2542ae4/libfuzzer/FuzzerUtilPosix.cpp:47
    #5 0x7fa5933bc88f  (/lib/x86_64-linux-gnu/libpthread.so.0+0x1288f)
    #6 0x7fa592ddfe96 in __libc_signal_restore_set /build/glibc-OTsEL5/glibc-2.27/signal/../sysdeps/unix/sysv/linux/nptl-signals.h:80
    #7 0x7fa592ddfe96 in gsignal /build/glibc-OTsEL5/glibc-2.27/signal/../sysdeps/unix/sysv/linux/raise.c:48
    #8 0x7fa592de1800 in abort /build/glibc-OTsEL5/glibc-2.27/stdlib/abort.c:79
    #9 0x558c330ae786 in std::sys::unix::abort_internal::hcede588431038b9d /rustc/f1b882b55805c342e46ee4ca3beeef1d1fa2044b/src/libstd/sys/unix/mod.rs:155:4
    #10 0x558c330a3b05 in std::process::abort::he25c37ef48eaa0ea /rustc/f1b882b55805c342e46ee4ca3beeef1d1fa2044b/src/libstd/process.rs:1575:13
    #11 0x558c33065edb in libfuzzer_sys::initialize::_$u7b$$u7b$closure$u7d$$u7d$::heffad3b6986886b5 /home/fitzgen/.cargo/git/checkouts/libfuzzer-sys-e07fde05820d7bc6/2542ae4/src/lib.rs:32:12
    #12 0x558c330a781f in std::panicking::rust_panic_with_hook::h2ab1adf2c285236e /rustc/f1b882b55805c342e46ee4ca3beeef1d1fa2044b/src/libstd/panicking.rs:468:16
    #13 0x558c330a72ed in std::panicking::continue_panic_fmt::h518931861486979c /rustc/f1b882b55805c342e46ee4ca3beeef1d1fa2044b/src/libstd/panicking.rs:373:4
    #14 0x558c330a722e in std::panicking::begin_panic_fmt::h66fe53e1a4a366e8 /rustc/f1b882b55805c342e46ee4ca3beeef1d1fa2044b/src/libstd/panicking.rs:328:4
    #15 0x558c30c30194 in wasmtime_environ::vmoffsets::VMOffsets::vmctx_vmmemory_definition::h215982e2895d3fdb /home/fitzgen/wasmtime/crates/environ/src/vmoffsets.rs:447:8
    #16 0x558c30c3117d in wasmtime_environ::vmoffsets::VMOffsets::vmctx_vmmemory_definition_base::h5b1100f39ff1c673 /home/fitzgen/wasmtime/crates/environ/src/vmoffsets.rs:522:8
    #17 0x558c2f53b529 in wasmtime_jit::compiler::Compiler::compile::h6a32e0cc4c4d646d /home/fitzgen/wasmtime/crates/jit/src/compiler.rs:169:20
    #18 0x558c2f556608 in wasmtime_jit::instantiate::RawCompiledModule::new::hc2c7e54ef375f5cf /home/fitzgen/wasmtime/crates/jit/src/instantiate.rs:78:72
    #19 0x558c2f559495 in wasmtime_jit::instantiate::instantiate::h7f64a5ced2b10b9f /home/fitzgen/wasmtime/crates/jit/src/instantiate.rs:264:14
    #20 0x558c2f1c8b45 in wasmtime_fuzzing::oracles::instantiate::hc5701bae16d3e3f6 /home/fitzgen/wasmtime/crates/fuzzing/src/oracles.rs:40:4
    #21 0x558c2f13bfcb in rust_fuzzer_test_input /home/fitzgen/wasmtime/fuzz/fuzz_targets/instantiate.rs:9:4
    #22 0x558c33065a7c in libfuzzer_sys::test_input_wrap::_$u7b$$u7b$closure$u7d$$u7d$::hd4177d4f47b65610 /home/fitzgen/.cargo/git/checkouts/libfuzzer-sys-e07fde05820d7bc6/2542ae4/src/lib.rs:11:8
    #23 0x558c33067697 in std::panicking::try::do_call::h098aa44adc274d5c /rustc/f1b882b55805c342e46ee4ca3beeef1d1fa2044b/src/libstd/panicking.rs:287:39
    #24 0x558c330aefc9 in __rust_maybe_catch_panic /rustc/f1b882b55805c342e46ee4ca3beeef1d1fa2044b/src/libpanic_unwind/lib.rs:81:7
    #25 0x558c330670a0 in std::panicking::try::h316267ea74f150e1 /rustc/f1b882b55805c342e46ee4ca3beeef1d1fa2044b/src/libstd/panicking.rs:265:12
    #26 0x558c33066a8c in std::panic::catch_unwind::hdba423ecbb0b831f /rustc/f1b882b55805c342e46ee4ca3beeef1d1fa2044b/src/libstd/panic.rs:395:8
    #27 0x558c3306560e in LLVMFuzzerTestOneInput /home/fitzgen/.cargo/git/checkouts/libfuzzer-sys-e07fde05820d7bc6/2542ae4/src/lib.rs:9:4
    #28 0x558c33070040 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /home/fitzgen/.cargo/git/checkouts/libfuzzer-sys-e07fde05820d7bc6/2542ae4/libfuzzer/FuzzerLoop.cpp:553
    #29 0x558c3306f8e1 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool*) /home/fitzgen/.cargo/git/checkouts/libfuzzer-sys-e07fde05820d7bc6/2542ae4/libfuzzer/FuzzerLoop.cpp:469
    #30 0x558c33070be6 in fuzzer::Fuzzer::MutateAndTestOne() /home/fitzgen/.cargo/git/checkouts/libfuzzer-sys-e07fde05820d7bc6/2542ae4/libfuzzer/FuzzerLoop.cpp:696
    #31 0x558c33071891 in fuzzer::Fuzzer::Loop(std::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) /home/fitzgen/.cargo/git/checkouts/libfuzzer-sys-e07fde05820d7bc6/2542ae4/libfuzzer/FuzzerLoop.cpp:831
    #32 0x558c3303f613 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /home/fitzgen/.cargo/git/checkouts/libfuzzer-sys-e07fde05820d7bc6/2542ae4/libfuzzer/FuzzerDriver.cpp:825
    #33 0x558c330388dc in main /home/fitzgen/.cargo/git/checkouts/libfuzzer-sys-e07fde05820d7bc6/2542ae4/libfuzzer/FuzzerMain.cpp:19
    #34 0x7fa592dc2b96 in __libc_start_main /build/glibc-OTsEL5/glibc-2.27/csu/../csu/libc-start.c:310
    #35 0x558c2f13bcb9 in _start (/home/fitzgen/wasmtime/fuzz/target/x86_64-unknown-linux-gnu/debug/instantiate+0xfc4cb9)
```

**Comment by fitzgen** [comment]
This is the assertion that is failing: https://github.com/bytecodealliance/wasmtime/blob/752ed901d6822f1296d26cfbece1ff17ed3ea5ef/crates/environ/src/vmoffsets.rs#L447

**Comment by sunfishcode** [comment]
Yay for fuzzing :-). The debugging code in compiler.rs is assuming it can access memory index 0, but that fails if there is no memory defined. It just needs to check if there's any memory first.
