### ISSUE TITLE
Panic when compiling invalid wasm with bad element segment count

### ISSUE THREAD

**Issue by fitzgen** [bytecodealliance/wasmtime#644]
Extract [invalid-segment-count.tar.gz](https://github.com/bytecodealliance/wasmtime/files/3894574/invalid-segment-count.tar.gz) to `crates/fuzzing/tests/regressions/invalid-elem-segment-count.wasm`

Append this to `crates/fuzzing/tests/regression.rs`:

```rust
#[test]
fn compile_invalid_elem_segment_count() {
    let data = include_bytes!("./regressions/invalid-elem-segment-count.wasm");
    oracles::compile(data, wasmtime_jit::CompilationStrategy::Cranelift);
}
```

Run `cargo test -p wasmtime-fuzzing` and get this panic:

```
test compile_invalid_elem_segment_count ... FAILED

failures:

---- compile_invalid_elem_segment_count stdout ----
thread 'compile_invalid_elem_segment_count' panicked at 'element items', src/libcore/option.rs:1187:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:84
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1030
   5: std::io::Write::write_fmt
             at /rustc/f1b882b55805c342e46ee4ca3beeef1d1fa2044b/src/libstd/io/mod.rs:1412
   6: std::io::impls::<impl std::io::Write for alloc::boxed::Box<W>>::write_fmt
             at src/libstd/io/impls.rs:141
   7: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   8: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   9: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
  10: std::panicking::default_hook
             at src/libstd/panicking.rs:202
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:464
  12: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:373
  13: rust_begin_unwind
             at src/libstd/panicking.rs:302
  14: core::panicking::panic_fmt
             at src/libcore/panicking.rs:82
  15: core::option::expect_failed
             at src/libcore/option.rs:1187
  16: core::option::Option<T>::expect
             at /rustc/f1b882b55805c342e46ee4ca3beeef1d1fa2044b/src/libcore/option.rs:347
  17: wasmparser::parser::Parser::read_element_entry_body
             at /home/fitzgen/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmparser-0.42.1/src/parser.rs:445
  18: wasmparser::parser::Parser::read_wrapped
             at /home/fitzgen/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmparser-0.42.1/src/parser.rs:917
  19: <wasmparser::parser::Parser as wasmparser::parser::WasmDecoder>::read
             at /home/fitzgen/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmparser-0.42.1/src/parser.rs:1055
  20: <wasmparser::validator::ValidatingParser as wasmparser::parser::WasmDecoder>::read
             at /home/fitzgen/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmparser-0.42.1/src/validator.rs:670
  21: <wasmparser::validator::ValidatingParser as wasmparser::parser::WasmDecoder>::read_with_input
             at /home/fitzgen/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmparser-0.42.1/src/validator.rs:689
  22: wasmparser::validator::validate
             at /home/fitzgen/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmparser-0.42.1/src/validator.rs:885
  23: wasmtime_fuzzing::oracles::compile
             at crates/fuzzing/src/oracles.rs:57
  24: regressions::compile_invalid_elem_segment_count
             at crates/fuzzing/tests/regressions.rs:19
  25: regressions::compile_invalid_elem_segment_count::{{closure}}
             at crates/fuzzing/tests/regressions.rs:17
  26: core::ops::function::FnOnce::call_once
             at /rustc/f1b882b55805c342e46ee4ca3beeef1d1fa2044b/src/libcore/ops/function.rs:223
  27: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/f1b882b55805c342e46ee4ca3beeef1d1fa2044b/src/liballoc/boxed.rs:942
  28: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:81
  29: std::panicking::try
             at /rustc/f1b882b55805c342e46ee4ca3beeef1d1fa2044b/src/libstd/panicking.rs:265
  30: std::panic::catch_unwind
             at /rustc/f1b882b55805c342e46ee4ca3beeef1d1fa2044b/src/libstd/panic.rs:395
  31: test::run_test_in_process
             at src/libtest/lib.rs:570
  32: test::run_test::run_test_inner::{{closure}}
             at src/libtest/lib.rs:473
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    compile_invalid_elem_segment_count

test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

**Comment by fitzgen** [comment]
cc @yurydelendik -- this seems to originate inside `wasmparser`

**Comment by fitzgen** [comment]
This got fixed upstream in `wasmparser` -- is there anything blocking the update in Wasmtime? Do we have to coordinate an update with cranelift as well?
