### ISSUE TITLE
Failure to instantiate a valid Wasm module

### ISSUE THREAD

**Issue by fitzgen** [bytecodealliance/wasmtime#659]
### Steps to reproduce

Copy the WAT test case to `wasmtime/crates/fuzzing/tests/regressions/my-regression.wat` and add the following test to `wasmtime/crates/fuzzing/tests/regressions.rs`:
    
```
#[test]
fn my_fuzzing_regression_test() {
    let data = wat::parse_str(
        include_str!("./regressions/my-regression.wat")
    ).unwrap();
    oracles::instantiate(data, CompilationStrategy::Auto)
}
```

<details>

<summary>WAT Test Case</summary>

```wasm
(module
      (type (;0;) (func (param i32)))
      (type (;1;) (func (param i32) (result i32)))
      (type (;2;) (func (param i32 i32)))
      (type (;3;) (func))
      (func (;0;) (type 0) (param i32))
      (func (;1;) (type 0) (param i32))
      (func (;2;) (type 1) (param i32) (result i32)
        i32.const 1)
      (func (;3;) (type 1) (param i32) (result i32)
        i32.const 2)
      (func (;4;) (type 2) (param i32 i32)
        local.get 0
        local.get 1
        i32.load offset=12
        call_indirect (type 1)
        drop)
      (func (;5;) (type 3)
        (local i32)
        global.get 0
        i32.const 16
        i32.sub
        local.tee 0
        global.set 0
        local.get 0
        i32.const 8
        i32.add
        i32.const 1024
        call 4
        local.get 0
        i32.const 8
        i32.add
        i32.const 1040
        call 4
        local.get 0
        i32.const 16
        i32.add
        global.set 0)
      (func (;6;) (type 3))
      (table (;0;) 5 5 funcref)
      (memory (;0;) 2)
      (global (;0;) (mut i32) (i32.const 66592))
      (export "memory" (memory 0))
      (export "foo" (func 5))
      (export "rust_eh_personality" (func 6))
      (elem (;0;) (i32.const 17) 0 2 1 3)
      (data (;0;) (i32.const 1024) "\01\00\00\00\00\00\00\00\01\00\00\00\02\00\00\00\03\00\00\00\00\00\00\00\01\00\00\00\04\00\00\00"))
```

</details>

### Panic Message

```
thread '<unnamed>' panicked at 'Failed to instantiate a valid Wasm module!: Instantiation failed during setup

Caused by:
    0: Failed to link module
    1: Link error: elements segment does not fit
```

<details>

<summary>Backtrace</summary>

```
    #0 0x55e7315f2f71 in __sanitizer_print_stack_trace /rustc/f1b882b55805c342e46ee4ca3beeef1d1fa2044b/src/llvm-project/compiler-rt/lib/asan/asan_stack.cc:86:3
    #1 0x55e7358b6ba1 in fuzzer::PrintStackTrace() /home/fitzgen/.cargo/git/checkouts/libfuzzer-sys-e07fde05820d7bc6/0c45075/libfuzzer/FuzzerUtil.cpp:205
    #2 0x55e7358ba7ba in fuzzer::Fuzzer::CrashCallback() /home/fitzgen/.cargo/git/checkouts/libfuzzer-sys-e07fde05820d7bc6/0c45075/libfuzzer/FuzzerLoop.cpp:232
    #3 0x55e7358ba65b in fuzzer::Fuzzer::StaticCrashSignalCallback() /home/fitzgen/.cargo/git/checkouts/libfuzzer-sys-e07fde05820d7bc6/0c45075/libfuzzer/FuzzerLoop.cpp:203
    #4 0x55e7358a51cb in fuzzer::CrashHandler(int, siginfo_t*, void*) /home/fitzgen/.cargo/git/checkouts/libfuzzer-sys-e07fde05820d7bc6/0c45075/libfuzzer/FuzzerUtilPosix.cpp:47
    #5 0x7f54dcdfa88f  (/lib/x86_64-linux-gnu/libpthread.so.0+0x1288f)
    #6 0x7f54dc81de96 in __libc_signal_restore_set /build/glibc-OTsEL5/glibc-2.27/signal/../sysdeps/unix/sysv/linux/nptl-signals.h:80
    #7 0x7f54dc81de96 in gsignal /build/glibc-OTsEL5/glibc-2.27/signal/../sysdeps/unix/sysv/linux/raise.c:48
    #8 0x7f54dc81f800 in abort /build/glibc-OTsEL5/glibc-2.27/stdlib/abort.c:79
    #9 0x55e7358f9b16 in std::sys::unix::abort_internal::hcede588431038b9d /rustc/f1b882b55805c342e46ee4ca3beeef1d1fa2044b/src/libstd/sys/unix/mod.rs:155:4
    #10 0x55e7358f32a5 in std::process::abort::he25c37ef48eaa0ea /rustc/f1b882b55805c342e46ee4ca3beeef1d1fa2044b/src/libstd/process.rs:1575:13
    #11 0x55e7358b2bfa in libfuzzer_sys::initialize::_$u7b$$u7b$closure$u7d$$u7d$::hdbf78e5b94455883 /home/fitzgen/.cargo/git/checkouts/libfuzzer-sys-e07fde05820d7bc6/0c45075/src/lib.rs:51:8
    #12 0x55e7358f70bf in std::panicking::rust_panic_with_hook::h2ab1adf2c285236e /rustc/f1b882b55805c342e46ee4ca3beeef1d1fa2044b/src/libstd/panicking.rs:468:16
    #13 0x55e7358f6b8d in std::panicking::continue_panic_fmt::h518931861486979c /rustc/f1b882b55805c342e46ee4ca3beeef1d1fa2044b/src/libstd/panicking.rs:373:4
    #14 0x55e7358f6a75 in rust_begin_unwind /rustc/f1b882b55805c342e46ee4ca3beeef1d1fa2044b/src/libstd/panicking.rs:302:4
    #15 0x55e7359127cd in core::panicking::panic_fmt::hb56c482d800280d0 /rustc/f1b882b55805c342e46ee4ca3beeef1d1fa2044b/src/libcore/panicking.rs:82:13
    #16 0x55e7359128c6 in core::result::unwrap_failed::h35329919e95da316 /rustc/f1b882b55805c342e46ee4ca3beeef1d1fa2044b/src/libcore/result.rs:1187:4
    #17 0x55e731612f6f in core::result::Result$LT$T$C$E$GT$::expect::h30f447eac1801da6 /rustc/f1b882b55805c342e46ee4ca3beeef1d1fa2044b/src/libcore/result.rs:982:22
    #18 0x55e73160d4f7 in wasmtime_fuzzing::oracles::instantiate::h6255b61826ae3859 /home/fitzgen/wasmtime/crates/fuzzing/src/oracles.rs:62:20
    #19 0x55e7315809e9 in rust_fuzzer_test_input /home/fitzgen/wasmtime/fuzz/fuzz_targets/instantiate.rs:8:42
    #20 0x55e7358b255c in libfuzzer_sys::test_input_wrap::_$u7b$$u7b$closure$u7d$$u7d$::hc2892c2eff9d5b8d /home/fitzgen/.cargo/git/checkouts/libfuzzer-sys-e07fde05820d7bc6/0c45075/src/lib.rs:27:8
    #21 0x55e7358e0c87 in std::panicking::try::do_call::hcc390cc34003f90d /rustc/f1b882b55805c342e46ee4ca3beeef1d1fa2044b/src/libstd/panicking.rs:287:39
    #22 0x55e7358fa359 in __rust_maybe_catch_panic /rustc/f1b882b55805c342e46ee4ca3beeef1d1fa2044b/src/libpanic_unwind/lib.rs:81:7
    #23 0x55e7358e0690 in std::panicking::try::hc195983d56e89a69 /rustc/f1b882b55805c342e46ee4ca3beeef1d1fa2044b/src/libstd/panicking.rs:265:12
    #24 0x55e7358b417c in std::panic::catch_unwind::h2a5bec9356a5108c /rustc/f1b882b55805c342e46ee4ca3beeef1d1fa2044b/src/libstd/panic.rs:395:8
    #25 0x55e7358b1dec in LLVMFuzzerTestOneInput /home/fitzgen/.cargo/git/checkouts/libfuzzer-sys-e07fde05820d7bc6/0c45075/src/lib.rs:25:21
    #26 0x55e7358bc298 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /home/fitzgen/.cargo/git/checkouts/libfuzzer-sys-e07fde05820d7bc6/0c45075/libfuzzer/FuzzerLoop.cpp:553
    #27 0x55e7358874d8 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /home/fitzgen/.cargo/git/checkouts/libfuzzer-sys-e07fde05820d7bc6/0c45075/libfuzzer/FuzzerDriver.cpp:292
    #28 0x55e73588b902 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /home/fitzgen/.cargo/git/checkouts/libfuzzer-sys-e07fde05820d7bc6/0c45075/libfuzzer/FuzzerDriver.cpp:775
    #29 0x55e73588501c in main /home/fitzgen/.cargo/git/checkouts/libfuzzer-sys-e07fde05820d7bc6/0c45075/libfuzzer/FuzzerMain.cpp:19
    #30 0x7f54dc800b96 in __libc_start_main /build/glibc-OTsEL5/glibc-2.27/csu/../csu/libc-start.c:310
    #31 0x55e7315805d9 in _start (/home/fitzgen/wasmtime/fuzz/target/x86_64-unknown-linux-gnu/debug/instantiate+0x10a25d9)
```

</details>

---------------------------------------------------------------

Note: I am not 100% sure this isn't a false alarm. Right now, we're assuming that Wasm that compiles OK should instantiate OK, but I need to double check if that is a valid assumption (ignoring things like OOM or not providing imports). In particular this seems maybe related to table initialization, and I thought that those bounds were checked (for non-imports) during validation time, not during instantiation time, but maybe that is not the case.

**Comment by fitzgen** [comment]
This is a false alarm.

Since initializing element segments into imported tables can't be checked until instantiation time, all table elements' indices are not checked until instantiation time. Our oracles need to handle this.

**Comment by fitzgen** [comment]
https://github.com/WebAssembly/testsuite/blob/master/elem.wast#L151
