### ISSUE TITLE
wasi-nn CI is failing

### ISSUE THREAD

**Issue by alexcrichton** [bytecodealliance/wasmtime#7125]
First seen [here](https://github.com/bytecodealliance/wasmtime/pull/7121#issuecomment-1742843388) the failure seems persistent:

```
Run abrown/install-openvino-action@v6
Run npm install
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

added 326 packages, and audited 327 packages in 5s

31 packages are looking for funding
  run `npm fund` for details

5 moderate severity vulnerabilities

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
Run node main.js
version: 2022.3.0
arch: x86_64
os: linux
Warning: downgrading jammy packages to focal; OpenVINO has no jammy packages but focal should work
release: ubuntu20
apt: true
running: bash src/apt.sh
md5sum: WARNING: 1 computed checksum did NOT match
/home/runner/work/_actions/abrown/install-openvino-action/v6/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB: FAILED
ERROR:  Command failed: bash src/apt.sh
{
  "status": 1,
  "signal": null,
  "output": [
    null,
    null,
    null
  ],
  "pid": 2300,
  "stdout": null,
  "stderr": null
}
Error: Command failed: bash src/apt.sh
    at checkExecSyncError (node:child_process:890:11)
    at Object.execFileSync (node:child_process:926:15)
    at bash (/home/runner/work/_actions/abrown/install-openvino-action/v6/main.js:91:19)
    at run (/home/runner/work/_actions/abrown/install-openvino-action/v6/main.js:56:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by alexcrichton** [comment]
cc @abrown, and I've submitted https://github.com/bytecodealliance/wasmtime/pull/7126 to temporarily disable wasi-nn in CI.

**Comment by abrown** [comment]
Opened https://github.com/bytecodealliance/wasmtime/pull/7164 to fix this.
