### ISSUE TITLE
[lightbeam] add overflow in debug mode (backend:store:2136 & backend:store:2159)

### ISSUE THREAD

**Issue by pventuzelo** [bytecodealliance/wasmtime#738]
# Issue description

An addition with overflow make lightbeam to panic when compiled in debug mode.

``` sh
$ ./target/debug/debug_lightbeam store_add_overflow_lightbeam.wasm 
thread 'main' panicked at 'attempt to add with overflow', XXX/wasmtime/crates/lightbeam/src/backend.rs:2136:68
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

This issue is related to the macro `store!` when dealing with the `i32.store8` opcode:

https://github.com/bytecodealliance/wasmtime/blob/31472fbb5a6417ea3d9eb10417ff5ea49712998a/crates/lightbeam/src/backend.rs#L2133-L2138

# Reproduction

Download: 
[store_add_overflow_lightbeam.zip](https://github.com/bytecodealliance/wasmtime/files/3978628/store_add_overflow_lightbeam.zip)

or `wasm2wat store_add_overflow_lightbeam.wasm
`:
``` wat
(module
  (type (;0;) (func))
  (func (;0;) (type 0)
    i32.const 2
    i32.const 1
    i32.store8 offset=2147483647)
  (memory (;0;) 1)
  (export "_start" (func 0)))
```

Testing program (need to be compiled in debug mode i.e. `RUSTFLAGS=-g cargo build`):

``` rust
use std::env;
use std::fs::{File};
use std::io;
use std::io::Read;
use std::path::PathBuf;

use wasmtime_fuzzing::oracles;
use wasmtime_jit::CompilationStrategy;
use lightbeam;

/// Read the contents of a file
fn read_contents(path: &PathBuf) -> Result<Vec<u8>, io::Error> {
    let mut buffer: Vec<u8> = Vec::new();
    let mut file = File::open(path)?;
    file.read_to_end(&mut buffer)?;
    drop(file);
    Ok(buffer)
}

fn main() {
	let args: Vec<String> = env::args().collect();
	let wasm_path = std::path::PathBuf::from(&args[1]);
	let wasm_binary: Vec<u8> = read_contents(&wasm_path).unwrap();

    let _res_compile = oracles::compile(&wasm_binary[..], CompilationStrategy::Lightbeam);
    let _res_instantiate = oracles::instantiate(&wasm_binary[..], CompilationStrategy::Lightbeam);
    let _res_translate = lightbeam::translate(&wasm_binary[..]);
}
```

wasmtime commit: 31472fbb5a6417ea3d9eb10417ff5ea49712998a

**Comment by pventuzelo** [comment]
Another addition overflow is in this part of the `store` macro:

https://github.com/bytecodealliance/wasmtime/blob/31472fbb5a6417ea3d9eb10417ff5ea49712998a/crates/lightbeam/src/backend.rs#L2157-L2160

Crash:
``` sh
$ debug_diff_compile panic_add_overflow_2159.wasm 
thread 'main' panicked at 'attempt to add with overflow', wasmtime/crates/lightbeam/src/backend.rs:2159:68
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

Reproduction:
``` wat
(module
  (type (;0;) (func))
  (func (;0;) (type 0)
    i32.const 2
    i32.const 1
    i32.store offset=2147483647 align=1
    unreachable)
  (memory (;0;) 1)
  (export "_start" (func 0)))
```

**Comment by alexcrichton** [comment]
Lightbeam was removed in https://github.com/bytecodealliance/wasmtime/pull/3390 as explained in [RFC 14](https://github.com/bytecodealliance/rfcs/pull/14), so I'm going to close this.
