### ISSUE TITLE
The http_outbound_request_get test is flaky

### ISSUE THREAD

**Issue by alexcrichton** [bytecodealliance/wasmtime#7430]
Seen [here](https://github.com/bytecodealliance/wasmtime/actions/runs/6688025014/job/18169481614) the failure is:

<details>

```
failures:

---- sync::http_outbound_request_get stdout ----
[guest] stderr:
thread 'main' panicked at crates\test-programs\src\bin\http_outbound_request_get.rs:15:6:
called `Result::unwrap()` on an `Err` value: /get

Caused by:
    Error::ProtocolError("operation was canceled: connection error: A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied. (os error 10057)")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

===
Error: error while executing at wasm backtrace:
    0: 0x2454f - panic_abort::__rust_start_panic::abort::h77cd51e7b0d065c7
                    at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/panic_abort/src/lib.rs:84:17              - __rust_start_panic
                    at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/panic_abort/src/lib.rs:38:5
    1: 0x24337 - rust_panic
                    at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:757:25
    2: 0x24314 - std::panicking::rust_panic_with_hook::hc93abff18edee779
                    at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:729:5
    3: 0x2367e - std::panicking::begin_panic_handler::{{closure}}::h922bcdd9c6fdedfb
                    at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:599:13
    4: 0x235ab - std::sys_common::backtrace::__rust_end_short_backtrace::h2597d6ecb1d3419e
                    at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:170:18
    5: 0x23c2f - rust_begin_unwind
                    at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
    6: 0x2923b - core::panicking::panic_fmt::h35d9e7e9c02f9eb5
                    at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
    7: 0x2b0e6 - core::result::unwrap_failed::hdced1445f29366eb
                    at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/result.rs:1652:5
    8: 0x35cd - core::result::Result<T,E>::unwrap::h1355d34690da57fd
                    at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/result.rs:1077:23
    9: 0x5277 - http_outbound_request_get::main::h8219f30c25bef7d9
                    at D:\a\wasmtime\wasmtime\crates\test-programs\src\bin\http_outbound_request_get.rs:6:15
   10: 0x2178 - core::ops::function::FnOnce::call_once::h12a50c11e9147483
                    at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:250:5
   11: 0x214f - std::sys_common::backtrace::__rust_begin_short_backtrace::h6827cbf24871499b
                    at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:154:18
   12: 0x2230 - std::rt::lang_start::{{closure}}::h3c805b20ec0f6801
                    at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/rt.rs:166:18
   13: 0x20d73 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h0b93d3876ad4840c
                    at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:284:13              - std::panicking::try::do_call::hc764fb4eb623a956
                    at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:502:40              - std::panicking::try::hde3a9d11fc0e2f9f
                    at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:466:19              - std::panic::catch_unwind::hacffbe76056a4c10
                    at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panic.rs:142:14              - std::rt::lang_start_internal::{{closure}}::h936a9958dd4643bc
                    at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/rt.rs:148:48              - std::panicking::try::do_call::h3d9522d1ead9d7d1
                    at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:502:40              - std::panicking::try::hd9bf6a95093e812b
                    at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:466:19              - std::panic::catch_unwind::he046bc591d4249e4
                    at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panic.rs:142:14              - std::rt::lang_start_internal::h394de9c4666f4612
                    at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/rt.rs:148:20
   14: 0x21db - std::rt::lang_start::hb005f5b90439b747
                    at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/rt.rs:165:17
   15: 0x5a0b - <unknown>!__main_void
   16: 0x212a - <unknown>!_start
   17: 0x311b0a - wit-component:adapter:wasi_snapshot_preview1!wasi:cli/run@0.2.0-rc-2023-11-05#run

Caused by:
    wasm trap: wasm `unreachable` instruction executed


failures:
    sync::http_outbound_request_get

test result: FAILED. 23 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 66.67s
```

</details>

Currently only seen on MinGW in CI (Windows). Wasn't able to reproduce locally. I remember seeing this before in CI once but I don't have a link to it.

**Comment by alexcrichton** [comment]
[Another failure](https://github.com/bytecodealliance/wasmtime/actions/runs/6738429091/job/18317992696), this time on MSVC

**Comment by alexcrichton** [comment]
Haven't seen this in awhile
